def acciones_lista_repaso():
    print "============================================================================================================================================================"
    print "============================================================================================================================================================" 
    print "===================================================================ENHORABUENA=============================================================================="
    print "============================================================================================================================================================"
    print "Ya sabes tratar listas , hemos practicado : "
    print "LISTAS continuar (14)"
    print "ORDENADAR LISTAS INT[SORT] - continuar(15)"
    print "ORDENADAR LISTAS DE STRING CON [SORT] continuar(16)"
    print "INVERTIR LISTAS [REVERSER] continuar(17)"
    print "ASIGNACION DE 1 ELEMENTO A LA DERECHA [APPEND] continuar(18)"
    print "ASIGNACION DE VARIOS VALORES POR SU DERECHA [EXTEND] continuar (19)"
    print "ASIGNACION DE ELEMENTOS EN UNA POSICION DETERMINADA [INSERT] continuar(20)"
    print "ELIMINAR ITEMS POR SU PROPIO VALOR [REMOVE] continuar(21)"
    print "ELIMINAR ITEMS POR SU POSICION[DEL] continuar(22"
    print "ELIMINAR ITEMS POR SU POSICION RETORNANDO EL ITEM ELIMINADO[POP]continuar(23)"
    print "ELIMINAR TODOS LOS ELEMENTOS CON LA FUNCION [DEL]continuar(24)"
    print "MODIFICAR ITEMS POR SU POSICION DE INDICE continuar(25)"
    print "MODIFICAR ITEMS POR SU POSICION DE INDICE EN UN RANGO DE INDICES continuar(26)"
    print "RESUMEN LISTAS continuar(27)"
    print "ASOCIAR OBJETOS A ELEMENTOS DE UNA LISTA/TUPLA continuar(28)"
    print "ASOCIAR OBJETOS A ELEMENTOS DE UNA LISTA/TUPLA POR INDICE DE RANGO continuar(29)"
