def resumen_acceso():
    print "============================================================================================================================================================"
    print "============================================================================================================================================================" 
    print "===================================================================ENHORABUENA=============================================================================="
    print "============================================================================================================================================================"

    print "vamos a echar un ojo atras para repasar los conocimientos adquiridos :"
    print "hemos visto las diferencias sintacticas que hay entre una tupla y una lista : "
    print "tupla=(1,2,3,4) la tupla usa parentesis"
    print "lista=[1,2,3,4] la lista va entre-corchetes"
    print "Sabemos que las tuplas son estaticas y las listas dinamicas"
    print "hemos aprendido a declarar tanto tuplas como listas"
    print "acceder a sus elementos por su indice de componente aunque tenga 1 o mas elementos y recoger la informacion como mejor nos convenga[desde:hasta:numero_saltos]"
    print "sabemos como individualizar los elementos multiples y tratarlos de forma indivudual"
    print "sabemos crear tuplas/listas numericas con range"
    print "sabemos como enumerar las listas/tuplas con su numero de indice y valor"
    print "sabemos como obetener el numero de indice por su valor con index"
    print "sabemos como contar cada elemento con count"
    print "y todo esto sirve tanto para listas como para tuplas, como habras observado todas estas operaciones son solo de consulta "
    print "sabemos como obtener el valor de un elemento, el valor de un indice, saber cuantas veces aparace, enumerarlo"
    print "y todas estas opciones coinciden en que ninguna modifica nada en todo caso inicializa como range una variable a un determinado rango de elementos"
    print "y como mucho hacer conversiones entre listas tuplas y viceversa pero el resto nos dara solo informacion que podremos tratar"
    print "Hasta aqui hemos recorrido la cantidad de opciones que manejan las tuplas que de la misma manera es aplicable a las listas"
    print "y apartir de aqui las siguientes cosas que veamos solo podran ser aplicadas a las listas"
    print "TUPALS: continuar(0) /tuplas"
    print "ACCESO A LOS ITEMS POR EL INDICE: continuar(1)"
    print "TUPLAS 1 DIMENSIONES RANGO POR EL INDICE: continuar(2)"
    print "AHORA CON LOS 3 ARGUMENTOS: continuar(4) "
    print "CREAR LISTAS/TUPLAS CON RANGE: continuar(5) "
    print "ENUMERAR EL INDICE[ENUMERATE]: continuar(6) "
    print "ENUMERAR UNA LISTA POR EL INDICE CON [ENUMERATE]: continuar(7) "
    print "OBTENER LA POSICION DEL ELEMENTO POR SU VALOR [INDEX]: continuar(8) "
    print "SABER CUANTAS VECES APARECE UN ELEMENTO EN UNA LISTA [COUNT]: continuar(9) "
    print "SABER CUANTAS VECES APARECE UN ELEMENTO EN UNA TUPLA [COUNT]: continuar(10) "
    print "SABER LA CANTIDAD DE ELEMENTOS DE UNA LISTA/TUPLA [LEN]: continuar(11) "
    print "CONVERSIONES ENTRE LISTAS TUPLAS Y VICIVERSA: continuar(12) "
    print "RESUMEN E INDICE: continuar(13) "
    print "cuando quieras seguir aprendiendo mas sobre las funionalidades extra que diferencia una lista de una tupla hazmelo saber escbribiendo continuar(14)"
